spring:
  cloud:
    nacos:
      discovery:
          server-addr: 127.0.0.1:8848

  application:
    name: gulimall-cart

  redis:
    host: 10.211.55.4
    port: 6379
  session:
    store-type: redis


server:
  port: 40000

gulimall:
  thread:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveTime: 300
